# Generated by Django 5.1.5 on 2025-01-29 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segunda_parte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platotipico',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
