# Generated by Django 5.1.5 on 2025-01-29 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segunda_parte', '0002_platotipico_creado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platotipico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segunda_parte.categoria'),
        ),
    ]
